name: Publish Pre Release Version
on:
  workflow_dispatch:
defaults:
  run:
    shell: pwsh
env:
  ci_pipeline: true
  PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
jobs:
  publish-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "" # Remove any prefix to ensure compatibility for all build types
          pre_release_branches: ^((?!main).)*$
      - name: build.ps1 init
        run: ./build.ps1 init ${{ steps.tag_version.outputs.new_tag }}
      - name: build.ps1 compose
        run: ./build.ps1 compose ${{ steps.tag_version.outputs.new_tag }}
      - name: build.ps1 publish
        run: ./build.ps1 publish ${{ steps.tag_version.outputs.new_tag }}
